package builtin

// Code generated by parser.Generator. DO NOT EDIT.

// See github.com/ctx42/gomake/internal/parser.NewGenerator function.

import (
	"github.com/ctx42/gomake/internal/mkf"
)

// targetsBuiltIn returns slice of targets named "BuiltIn".
func targetsBuiltIn() []*mkf.Target {
	targets := make([]*mkf.Target, 0)
	return targets
}
