// Code generated by 00_generate_versions.go. DO NOT EDIT.

package osarch

// Generated from Go 1.26 (go tool dist list).

// goos lists every GOOS value supported by Go.
var goos = []string{"aix", "android", "darwin", "dragonfly", "freebsd", "illumos", "ios", "js", "linux", "netbsd", "openbsd", "plan9", "solaris", "wasip1", "windows"}

// goarch lists every GOARCH value supported by Go.
var goarch = []string{"386", "amd64", "arm", "arm64", "loong64", "mips", "mips64", "mips64le", "mipsle", "ppc64", "ppc64le", "riscv64", "s390x", "wasm"}
