// SPDX-FileCopyrightText: (c) 2026 Rafal Zajac
// SPDX-License-Identifier: MIT

package parser

import (
	"bytes"
	"errors"
	"os"
	"text/template"

	"github.com/ctx42/gomake/internal/mkf"
)

// MainName represents "main" package name.
const MainName = "main"

// CreateFile is a helper function writing code to file at given path.
func CreateFile(dst string, code []byte) error {
	return os.WriteFile(dst, code, 0600)
}

// GenOpt is signature for [Generator.Generate] option.
type GenOpt func(*genOpts)

// WithGenNames is [Generator.Generate] option setting package name to use for
// generated code and name suffix for the generated method.
func WithGenNames(name, suffix string) GenOpt {
	return func(opts *genOpts) {
		opts.pkg = name
		opts.suffix = suffix
	}
}

// WithGenReg is [Generator.Generate] option to generate "init" function.
var WithGenReg GenOpt = func(opts *genOpts) { opts.register = true }

// genOpts represents Generator configuration options.
type genOpts struct {
	pkg      string // Package name for the generated code.
	suffix   string // Function name suffix.
	register bool   // Generate "init" function registering the targets.
}

// defGenOpts returns default Generator configuration options.
func defGenOpts() genOpts {
	return genOpts{
		pkg:      MainName,
		suffix:   "Main",
		register: false,
	}
}

// Generator knows how to generate code for file defining targets.
//
// The generated file will have a function returning definitions. When
// constructor option WithGenReg is provided the generator will include code
// for init function registering the targets in global "targets" slice.
type Generator struct {
	tgs *Targets // Targets to generate code for.
}

// NewGenerator returns a new instance of [Generator] for provided targets.
//
// By default, destination package name will be set to "main", generated method
// name will have no suffix and "init" function code will not be generated.
func NewGenerator(tgs *Targets) *Generator {
	return &Generator{tgs: tgs}
}

// Generate generates the target-definitions source code.
func (gen *Generator) Generate(opts ...GenOpt) ([]byte, error) {
	def := defGenOpts()
	for _, opt := range opts {
		opt(&def)
	}
	if def.suffix == "" {
		return nil, errors.New("generated method suffix cannot be empty")
	}

	qualifyPkg := true
	renderImps := true
	renderImpCtx := true
	renderImpRing := true
	if def.pkg == MainName {
		qualifyPkg = false
		if gen.tgs.Len() == 0 {
			renderImps = false
		}
	}

	if gen.tgs.Len() == 0 {
		renderImpCtx = false
		renderImpRing = false
	}

	buf := &bytes.Buffer{}
	data := map[string]any{
		"package":             def.pkg,
		"qualify":             qualifyPkg,
		"imports":             gen.tgs.GoImports(),
		"imports_render":      renderImps,
		"imports_render_ctx":  renderImpCtx,
		"imports_render_ring": renderImpRing,
		"fn_name_suffix":      def.suffix,
		"register_targets":    def.register,
		"targets":             gen.tgs.GoCode(qualifyPkg),
	}
	if err := tgsTplParsed.Execute(buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// tgsTplParsed represents parsed tgsTpl template.
var tgsTplParsed = template.Must(
	template.New("targets").
		Funcs(map[string]any{"indent": mkf.Indent}).
		Parse(tgsTpl),
)

// tgsTpl represents "targets.go" template.
const tgsTpl = `package {{ .package }}

// Code generated by parser.Generator. DO NOT EDIT.

// See github.com/ctx42/gomake/internal/parser.NewGenerator function.
{{ if .imports_render }}
import (
{{- if .imports_render_ctx }}
	"context"
{{ end -}}
{{- if .imports_render_ring }}
	"github.com/ctx42/ring/pkg/ring"
{{ end -}}
{{ if .qualify }}
	"github.com/ctx42/gomake/internal/mkf"
{{ end -}}
{{ .imports | indent 1 -}}
)
{{ end }}
{{- if .register_targets }}
func init() { targets = append(targets, targets{{ .fn_name_suffix }}()...) }
{{ end -}}
{{ if .fn_name_suffix }}
// targets{{ .fn_name_suffix }} returns slice of targets named "{{ .fn_name_suffix }}".
{{- else -}}
// targets returns slice of targets.
{{- end }}
func targets{{ .fn_name_suffix }}() []*{{if .qualify }}mkf.{{end}}Target {
{{ .targets | indent 1}}
	return targets
}
`
